version: '3.8'

services:
  chirpid-backend-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - PORT=5001
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Mount uploads directory for persistence
      - ./app/uploads:/app/app/uploads
      # Mount database for persistence
      - ./database:/app/database
    restart: unless-stopped
    command: ["python", "server/run.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
