version: '3.8'

services:
  backend:
    build: .
    # image: <BACKEND_IMAGE>
    container_name: chirpid-backend
    restart: unless-stopped
    expose:
      - "5001"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - PORT=5001
    volumes:
      - ./app/uploads:/app/app/uploads
      - ./database:/app/database
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

  nginx:
    image: nginx:alpine
    container_name: chirpid-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  letsencrypt:
    external: true
